/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiEmployeeRouteImport } from './routes/api/ai-employee'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app.settings'
import { Route as AuthenticatedAppScheduleRouteImport } from './routes/_authenticated/_app.schedule'
import { Route as AuthenticatedAppOperationsRouteImport } from './routes/_authenticated/_app.operations'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/_app.integrations'
import { Route as AuthenticatedAppEmployeesRouteImport } from './routes/_authenticated/_app.employees'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app.dashboard'
import { Route as AuthenticatedAppCustomersRouteImport } from './routes/_authenticated/_app.customers'
import { Route as AuthenticatedAppAutomationsRouteImport } from './routes/_authenticated/_app.automations'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/_app.audit'
import { Route as AuthenticatedAppAnalyticsRouteImport } from './routes/_authenticated/_app.analytics'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/_app.ai'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiEmployeeRoute = ApiAiEmployeeRouteImport.update({
  id: '/api/ai-employee',
  path: '/api/ai-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScheduleRoute =
  AuthenticatedAppScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOperationsRoute =
  AuthenticatedAppOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmployeesRoute =
  AuthenticatedAppEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCustomersRoute =
  AuthenticatedAppCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAutomationsRoute =
  AuthenticatedAppAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAnalyticsRoute =
  AuthenticatedAppAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai-employee': typeof ApiAiEmployeeRoute
  '/ai': typeof AuthenticatedAppAiRoute
  '/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/automations': typeof AuthenticatedAppAutomationsRoute
  '/customers': typeof AuthenticatedAppCustomersRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/employees': typeof AuthenticatedAppEmployeesRoute
  '/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/operations': typeof AuthenticatedAppOperationsRoute
  '/schedule': typeof AuthenticatedAppScheduleRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/ai-employee': typeof ApiAiEmployeeRoute
  '/ai': typeof AuthenticatedAppAiRoute
  '/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/audit': typeof AuthenticatedAppAuditRoute
  '/automations': typeof AuthenticatedAppAutomationsRoute
  '/customers': typeof AuthenticatedAppCustomersRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/employees': typeof AuthenticatedAppEmployeesRoute
  '/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/operations': typeof AuthenticatedAppOperationsRoute
  '/schedule': typeof AuthenticatedAppScheduleRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/api/ai-employee': typeof ApiAiEmployeeRoute
  '/_authenticated/_app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/_app/analytics': typeof AuthenticatedAppAnalyticsRoute
  '/_authenticated/_app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/_app/automations': typeof AuthenticatedAppAutomationsRoute
  '/_authenticated/_app/customers': typeof AuthenticatedAppCustomersRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/employees': typeof AuthenticatedAppEmployeesRoute
  '/_authenticated/_app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/_app/operations': typeof AuthenticatedAppOperationsRoute
  '/_authenticated/_app/schedule': typeof AuthenticatedAppScheduleRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api/ai-employee'
    | '/ai'
    | '/analytics'
    | '/audit'
    | '/automations'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/integrations'
    | '/operations'
    | '/schedule'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/api/ai-employee'
    | '/ai'
    | '/analytics'
    | '/audit'
    | '/automations'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/integrations'
    | '/operations'
    | '/schedule'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/_app'
    | '/api/ai-employee'
    | '/_authenticated/_app/ai'
    | '/_authenticated/_app/analytics'
    | '/_authenticated/_app/audit'
    | '/_authenticated/_app/automations'
    | '/_authenticated/_app/customers'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/employees'
    | '/_authenticated/_app/integrations'
    | '/_authenticated/_app/operations'
    | '/_authenticated/_app/schedule'
    | '/_authenticated/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAiEmployeeRoute: typeof ApiAiEmployeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-employee': {
      id: '/api/ai-employee'
      path: '/api/ai-employee'
      fullPath: '/api/ai-employee'
      preLoaderRoute: typeof ApiAiEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/schedule': {
      id: '/_authenticated/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedAppScheduleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/operations': {
      id: '/_authenticated/_app/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthenticatedAppOperationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/integrations': {
      id: '/_authenticated/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/employees': {
      id: '/_authenticated/_app/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedAppEmployeesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/customers': {
      id: '/_authenticated/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedAppCustomersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/automations': {
      id: '/_authenticated/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAppAutomationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/audit': {
      id: '/_authenticated/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/analytics': {
      id: '/_authenticated/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAppAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/ai': {
      id: '/_authenticated/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppAnalyticsRoute: typeof AuthenticatedAppAnalyticsRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppAutomationsRoute: typeof AuthenticatedAppAutomationsRoute
  AuthenticatedAppCustomersRoute: typeof AuthenticatedAppCustomersRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppEmployeesRoute: typeof AuthenticatedAppEmployeesRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppOperationsRoute: typeof AuthenticatedAppOperationsRoute
  AuthenticatedAppScheduleRoute: typeof AuthenticatedAppScheduleRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppAnalyticsRoute: AuthenticatedAppAnalyticsRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppAutomationsRoute: AuthenticatedAppAutomationsRoute,
  AuthenticatedAppCustomersRoute: AuthenticatedAppCustomersRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppEmployeesRoute: AuthenticatedAppEmployeesRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppOperationsRoute: AuthenticatedAppOperationsRoute,
  AuthenticatedAppScheduleRoute: AuthenticatedAppScheduleRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAiEmployeeRoute: ApiAiEmployeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
